"use client";

import { useState, useEffect, useCallback } from "react";
import { cn } from "@/lib/utils";
import {
  BarChart3,
  Database,
  Zap,
  DollarSign,
  TrendingUp,
  CheckCircle2,
  FlaskConical,
  ShieldCheck,
  Activity,
  RefreshCw,
  BookOpen,
  AlertTriangle,
  Info,
  Trophy,
} from "lucide-react";
import type {
  BenchmarkResults,
  ModelResult,
  PioneerJobMetrics,
  AnnotationCounts,
} from "@/lib/benchmark-eval";

// ── Static model metadata ─────────────────────────────────────────────────────

interface ModelMeta {
  id: string;
  label: string;
  sublabel: string;
  isOurs?: boolean;
  source: "live" | "published";
  bar: string;
  text: string;
  costPer1k: number;
  /**
   * true = training data was generated by Claude → Claude's score on this eval
   * is inflated because it's grading its own output style. Show caveat badge.
   */
  contaminated?: boolean;
}

const MODEL_META: ModelMeta[] = [
  {
    id: "pioneer-ft",
    label: "Pioneer GLiNER2",
    sublabel: "Fine-tuned · Your model",
    isOurs: true,
    source: "live",
    bar: "bg-[#22c55e]",
    text: "text-[#22c55e]",
    costPer1k: 0.03,
  },
  {
    id: "claude35",
    label: "Claude Sonnet",
    sublabel: "Frontier LLM · 5-shot",
    source: "live",
    bar: "bg-white/30",
    text: "text-white/55",
    costPer1k: 19.8,
    // Training data was generated by Claude. Claude scores better on Claude-
    // generated eval examples than it would on real documents.
    contaminated: true,
  },
  {
    id: "gpt4o",
    label: "GPT-4o",
    sublabel: "Frontier LLM · 5-shot",
    source: "live",
    bar: "bg-white/22",
    text: "text-white/50",
    costPer1k: 14.2,
  },
  {
    id: "gliner-base",
    label: "GLiNER2 Base",
    sublabel: "Zero-shot baseline",
    source: "live",
    bar: "bg-white/16",
    text: "text-white/45",
    costPer1k: 0.03,
  },
  {
    id: "bert",
    label: "BERT-NER",
    sublabel: "Published baseline · CrossNER",
    source: "published",
    bar: "bg-white/10",
    text: "text-white/30",
    costPer1k: 0.04,
  },
  {
    id: "spacy",
    label: "spaCy TRF",
    sublabel: "Published baseline · CrossNER",
    source: "published",
    bar: "bg-white/[0.06]",
    text: "text-white/20",
    costPer1k: 0.0,
  },
];

const PUBLISHED_BASELINES: Record<
  string,
  { f1: number; precision: number; recall: number; latency_ms: number }
> = {
  bert: { f1: 73.1, precision: 75.9, recall: 70.4, latency_ms: 43 },
  spacy: { f1: 64.7, precision: 68.3, recall: 61.4, latency_ms: 12 },
};

const ENTITY_TYPES = [
  "agency",
  "regulation_name",
  "regulated_substance",
  "affected_product_category",
  "deadline",
  "jurisdiction",
  "penalty",
  "prohibited_claim",
];

const ENTITY_COLORS: Record<string, string> = {
  agency: "bg-white/40",
  regulation_name: "bg-white/32",
  regulated_substance: "bg-white/25",
  affected_product_category: "bg-white/20",
  deadline: "bg-[#22c55e]/50",
  jurisdiction: "bg-white/16",
  penalty: "bg-white/12",
  prohibited_claim: "bg-white/[0.08]",
};

/** Minimum annotations needed for the per-entity F1 to be statistically useful. */
const RELIABLE_ANNOTATION_THRESHOLD = 15;
const LOW_ANNOTATION_THRESHOLD = 8;

type BTab = "overview" | "entities" | "speed" | "training";

const BTABS: { id: BTab; label: string; Icon: typeof BarChart3 }[] = [
  { id: "overview", label: "Overview", Icon: BarChart3 },
  { id: "entities", label: "By Entity", Icon: ShieldCheck },
  { id: "speed", label: "Speed & Cost", Icon: Zap },
  { id: "training", label: "Training Data", Icon: Database },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

function Bar({
  value,
  max,
  colorClass,
}: {
  value: number;
  max: number;
  colorClass: string;
}) {
  return (
    <div className="flex-1 h-1.5 bg-white/[0.06] rounded-full overflow-hidden">
      <div
        className={cn(
          "h-full rounded-full transition-all duration-700",
          colorClass
        )}
        style={{ width: `${(value / max) * 100}%` }}
      />
    </div>
  );
}

function MetricBadge({
  value,
  suffix = "%",
  highlight,
}: {
  value: number | string;
  suffix?: string;
  highlight?: boolean;
}) {
  return (
    <span
      className={cn(
        "text-[12px] font-semibold tabular-nums",
        highlight ? "text-[#22c55e]" : "text-white/60"
      )}
    >
      {typeof value === "number" ? value.toFixed(1) : value}
      {suffix}
    </span>
  );
}

function Micro({ label, value }: { label: string; value: number }) {
  return (
    <span className="text-[9px] text-white/25 font-mono">
      {label} <span className="text-white/40">{value.toFixed(1)}</span>
    </span>
  );
}

function Section({
  label,
  hint,
  Icon,
  children,
  badge,
}: {
  label: string;
  hint?: string;
  Icon: typeof BarChart3;
  children: React.ReactNode;
  badge?: React.ReactNode;
}) {
  return (
    <div className="space-y-3">
      <div className="flex items-start gap-2">
        <Icon size={11} className="text-white/25 mt-0.5 shrink-0" />
        <div className="flex-1">
          <div className="flex items-center gap-2">
            <p className="text-[9px] font-mono uppercase tracking-widest text-white/30">
              {label}
            </p>
            {badge}
          </div>
          {hint && (
            <p className="text-[10px] text-white/20 mt-0.5">{hint}</p>
          )}
        </div>
      </div>
      {children}
    </div>
  );
}

function MiniStat({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-black px-3 py-2.5 space-y-0.5">
      <p className="text-[8px] font-mono uppercase tracking-widest text-white/25">
        {label}
      </p>
      <p className="text-[14px] font-semibold text-white/70">{value}</p>
    </div>
  );
}

function getScore(
  modelId: string,
  data: BenchmarkResults | null
): { f1: number; precision: number; recall: number; latency_ms: number } | null {
  const live = data?.models[modelId];
  if (live) return live;
  return PUBLISHED_BASELINES[modelId] ?? null;
}

// ── Pioneer Validation Card ───────────────────────────────────────────────────
/**
 * Shows Pioneer's own held-out validation metrics (most credible source).
 * These come from GET /felix/training-jobs/{id} on every page load.
 */
function PioneerValidationCard({
  metrics,
  baseScore,
}: {
  metrics: PioneerJobMetrics;
  baseScore: ModelResult | null;
}) {
  const gainVsBase =
    baseScore ? (metrics.f1 - baseScore.f1).toFixed(1) : null;
  const gainPositive = gainVsBase !== null && parseFloat(gainVsBase) >= 0;

  return (
    <div className="rounded-xl border border-[#22c55e]/25 bg-[#22c55e]/[0.04] px-4 py-4 space-y-3">
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <Trophy size={12} className="text-[#22c55e]/70" />
          <span className="text-[9px] font-mono uppercase tracking-widest text-[#22c55e]/60">
            Pioneer validation split · authoritative
          </span>
        </div>
        <span className="text-[8px] font-mono text-white/25 border border-white/[0.08] px-1.5 py-0.5 rounded-full">
          status: {metrics.status}
        </span>
      </div>

      <div className="grid grid-cols-3 gap-3">
        {[
          { label: "F1", value: metrics.f1 },
          { label: "Precision", value: metrics.precision },
          { label: "Recall", value: metrics.recall },
        ].map(({ label, value }) => (
          <div key={label} className="space-y-0.5">
            <p className="text-[8px] font-mono uppercase tracking-widest text-white/25">
              {label}
            </p>
            <p className="text-[22px] font-semibold text-[#22c55e] leading-none">
              {value.toFixed(1)}
              <span className="text-[13px] text-[#22c55e]/60">%</span>
            </p>
          </div>
        ))}
      </div>

      <div className="flex items-start gap-2 pt-1 border-t border-white/[0.06]">
        <Info size={9} className="text-white/25 mt-0.5 shrink-0" />
        <p className="text-[9px] text-white/30 leading-relaxed">
          Computed by Pioneer on its own held-out split (withheld before training
          began). More reliable than our 25-example comparison below — larger
          sample, independent split, no annotation-boundary artifacts.
          {gainVsBase !== null && (
            <>
              {" "}Fine-tuning gained{" "}
              <span
                className={gainPositive ? "text-[#22c55e]/70" : "text-red-400/70"}
              >
                {gainPositive ? "+" : ""}
                {gainVsBase} F1
              </span>{" "}
              over base.
            </>
          )}
        </p>
      </div>
    </div>
  );
}

// ── Contamination notice ──────────────────────────────────────────────────────

function ContaminationNotice() {
  return (
    <div className="flex items-start gap-2 rounded-lg border border-amber-400/15 bg-amber-400/[0.04] px-3 py-2.5">
      <AlertTriangle size={10} className="text-amber-400/50 mt-0.5 shrink-0" />
      <p className="text-[9px] text-white/30 leading-relaxed">
        <span className="text-amber-400/60 font-medium">Data contamination caveat:</span>{" "}
        Training data was generated by Claude (via Pioneer /generate). Evaluation
        examples were also written in Claude&apos;s style. Claude&apos;s scores are
        inflated vs. real documents — treat LLM comparison as indicative only.
        GPT-4o scores are more trustworthy as an independent reference.
      </p>
    </div>
  );
}

// ── F1 mode toggle ────────────────────────────────────────────────────────────

type F1Mode = "partial" | "strict";

function F1Toggle({
  mode,
  onChange,
}: {
  mode: F1Mode;
  onChange: (m: F1Mode) => void;
}) {
  return (
    <div className="flex items-center gap-0.5 rounded-md border border-white/[0.1] bg-white/[0.03] p-0.5 shrink-0">
      {(["partial", "strict"] as F1Mode[]).map((m) => (
        <button
          key={m}
          onClick={() => onChange(m)}
          className={cn(
            "px-2 py-0.5 rounded text-[9px] font-mono transition-colors",
            mode === m
              ? "bg-white/10 text-white/70"
              : "text-white/25 hover:text-white/45"
          )}
        >
          {m}
        </button>
      ))}
    </div>
  );
}

// ── Eval header ───────────────────────────────────────────────────────────────

function EvalHeader({
  data,
  cachedAt,
  running,
  error,
  onRun,
}: {
  data: BenchmarkResults | null;
  cachedAt: string | null;
  running: boolean;
  error: string | null;
  onRun: () => void;
}) {
  function ageLabel() {
    if (!cachedAt) return null;
    const diffMs = Date.now() - new Date(cachedAt).getTime();
    const diffMin = Math.floor(diffMs / 60_000);
    if (diffMin < 1) return "just now";
    if (diffMin < 60) return `${diffMin}m ago`;
    return `${Math.floor(diffMin / 60)}h ago`;
  }

  return (
    <div className="flex items-center justify-between gap-4 flex-wrap">
      <div>
        {data ? (
          <p className="text-[10px] text-white/30 font-mono">
            Cross-model comparison · {data.examplesCount} synthetic examples ·
            last run {ageLabel()}
          </p>
        ) : (
          <p className="text-[10px] text-white/30 font-mono">
            No comparison run yet — click to run all models on synthetic eval set
          </p>
        )}
        {error && (
          <p className="text-[10px] text-red-400/70 mt-0.5">{error}</p>
        )}
      </div>
      <button
        onClick={onRun}
        disabled={running}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-white/[0.12] bg-white/[0.04] text-[11px] font-medium text-white/60 hover:text-white hover:border-white/25 hover:bg-white/[0.08] transition-all disabled:opacity-40 disabled:cursor-not-allowed shrink-0"
      >
        <RefreshCw size={11} className={running ? "animate-spin" : ""} />
        {running
          ? "Running…"
          : data
          ? "Re-run comparison"
          : "Run comparison"}
      </button>
    </div>
  );
}

// ── Empty state ───────────────────────────────────────────────────────────────

function EmptyState({
  running,
  onRun,
  pioneerJobMetrics,
  baseScore,
}: {
  running: boolean;
  onRun: () => void;
  pioneerJobMetrics: PioneerJobMetrics | null;
  baseScore: ModelResult | null;
}) {
  return (
    <div className="space-y-4">
      {pioneerJobMetrics && (
        <PioneerValidationCard
          metrics={pioneerJobMetrics}
          baseScore={baseScore}
        />
      )}
      <div className="flex flex-col items-center justify-center py-10 text-center gap-4">
        <BarChart3 size={28} className="text-white/15" />
        <div>
          <p className="text-[13px] text-white/40 font-medium mb-1">
            No cross-model comparison yet
          </p>
          <p className="text-[11px] text-white/25 leading-relaxed max-w-sm">
            Click to run all models (GLiNER base + fine-tuned + Claude + GPT-4o)
            on the 25-example synthetic eval set. Results below Pioneer&apos;s
            held-out metrics above.
          </p>
        </div>
        <button
          onClick={onRun}
          disabled={running}
          className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white/[0.07] border border-white/[0.12] text-[12px] font-medium text-white/70 hover:text-white hover:bg-white/[0.1] hover:border-white/25 transition-all disabled:opacity-40"
        >
          <RefreshCw size={12} className={running ? "animate-spin" : ""} />
          {running ? "Running…" : "Run comparison"}
        </button>
        {running && (
          <p className="text-[10px] text-white/20 font-mono animate-pulse">
            Calling Pioneer API · GLiNER inference + LLM 5-shot · ~15–60s
          </p>
        )}
      </div>
    </div>
  );
}

// ── Overview tab ──────────────────────────────────────────────────────────────

function OverviewTab({
  data,
  pioneerJobMetrics,
  f1Mode,
}: {
  data: BenchmarkResults | null;
  pioneerJobMetrics: PioneerJobMetrics | null;
  f1Mode: F1Mode;
}) {
  if (!data) return null;

  const ftScore = data.models["pioneer-ft"] ?? null;
  const baseScore = data.models["gliner-base"] ?? null;
  const claudeScore = data.models["claude35"] ?? null;
  const gpt4oScore = data.models["gpt4o"] ?? null;

  const scored = MODEL_META.map((m) => ({
    meta: m,
    score: getScore(m.id, data),
  }))
    .filter((x) => x.score !== null)
    .sort((a, b) => {
      const af =
        f1Mode === "partial" && "f1_partial" in (a.score as ModelResult)
          ? (a.score as ModelResult).f1_partial
          : a.score!.f1;
      const bf =
        f1Mode === "partial" && "f1_partial" in (b.score as ModelResult)
          ? (b.score as ModelResult).f1_partial
          : b.score!.f1;
      return bf - af;
    });

  return (
    <div className="space-y-6">
      {/* Track A: Pioneer's own validation (most authoritative) */}
      {pioneerJobMetrics && (
        <PioneerValidationCard
          metrics={pioneerJobMetrics}
          baseScore={baseScore}
        />
      )}

      {/* Track B: Cross-model comparison on synthetic eval set */}
      <Section
        label="Cross-model comparison · 25 synthetic examples"
        hint={
          f1Mode === "partial"
            ? "Partial F1: span is correct if prediction is a substring of ground truth (or vice versa)"
            : "Strict F1: exact normalized span match required — more sensitive to boundary decisions"
        }
        Icon={TrendingUp}
      >
        <ContaminationNotice />
        <div className="space-y-2 mt-1">
          {scored.map(({ meta: m, score }) => {
            const isPublished = m.source === "published";
            const liveScore = score as ModelResult;
            const f1 =
              f1Mode === "partial" && "f1_partial" in liveScore
                ? liveScore.f1_partial
                : score!.f1;
            const precision =
              f1Mode === "partial" && "precision_partial" in liveScore
                ? liveScore.precision_partial
                : score!.precision;
            const recall =
              f1Mode === "partial" && "recall_partial" in liveScore
                ? liveScore.recall_partial
                : score!.recall;

            return (
              <div
                key={m.id}
                className={cn(
                  "rounded-lg px-3 py-2.5",
                  m.isOurs
                    ? "bg-[#22c55e]/[0.06] border border-[#22c55e]/20"
                    : "bg-white/[0.02] border border-white/[0.04]"
                )}
              >
                <div className="flex items-center gap-3 mb-1.5">
                  <div className="w-44 shrink-0">
                    <div className="flex items-center gap-1.5 flex-wrap">
                      <p
                        className={cn(
                          "text-[11px] font-medium leading-none",
                          m.isOurs
                            ? "text-white/90"
                            : isPublished
                            ? "text-white/35"
                            : "text-white/55"
                        )}
                      >
                        {m.label}
                      </p>
                      {m.isOurs && (
                        <span className="text-[8px] font-mono uppercase tracking-wider text-[#22c55e]/80 border border-[#22c55e]/30 px-1 py-0.5 rounded-full">
                          yours
                        </span>
                      )}
                      {isPublished && (
                        <span className="text-[8px] font-mono uppercase tracking-wider text-white/20 border border-white/10 px-1 py-0.5 rounded-full flex items-center gap-0.5">
                          <BookOpen size={7} />
                          paper
                        </span>
                      )}
                      {m.contaminated && !isPublished && (
                        <span className="text-[8px] font-mono text-amber-400/50 border border-amber-400/20 px-1 py-0.5 rounded-full flex items-center gap-0.5">
                          <AlertTriangle size={6} />
                          biased
                        </span>
                      )}
                    </div>
                    <p
                      className={cn(
                        "text-[9px] mt-0.5",
                        isPublished ? "text-white/18" : "text-white/25"
                      )}
                    >
                      {m.sublabel}
                    </p>
                  </div>
                  <Bar
                    value={f1}
                    max={100}
                    colorClass={isPublished ? "bg-white/15" : m.bar}
                  />
                  <MetricBadge value={f1} highlight={m.isOurs} />
                </div>
                <div className="flex gap-6 pl-[180px]">
                  <Micro label="P" value={precision} />
                  <Micro label="R" value={recall} />
                </div>
              </div>
            );
          })}
        </div>
        <p className="text-[9px] text-white/20 mt-3 leading-relaxed">
          GLiNER evaluated via Pioneer /inference at threshold 0.35. LLMs use
          5-shot JSON extraction. BERT/spaCy from CrossNER paper.{" "}
          <span className="text-amber-400/40">
            ⚠ Training data is Claude-generated — Claude scores are systematically
            inflated. Use Pioneer validation card above for authoritative fine-tune
            metrics.
          </span>
        </p>
      </Section>

      {/* Delta callouts — only show for GLiNER comparison (uncontaminated) */}
      {(ftScore || baseScore) && (
        <div className="grid grid-cols-2 gap-3">
          {ftScore && baseScore && pioneerJobMetrics && (
            <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 space-y-1">
              <p className="text-[9px] font-mono uppercase tracking-widest text-white/25">
                Pioneer validated gain
              </p>
              <p
                className={cn(
                  "text-[22px] font-semibold leading-none",
                  pioneerJobMetrics.f1 - baseScore.f1 >= 0
                    ? "text-[#22c55e]"
                    : "text-red-400"
                )}
              >
                {pioneerJobMetrics.f1 - baseScore.f1 >= 0 ? "+" : ""}
                {(pioneerJobMetrics.f1 - baseScore.f1).toFixed(1)}
                <span className="text-[13px]"> F1</span>
              </p>
              <p className="text-[10px] text-white/30 leading-snug">
                Pioneer held-out vs synthetic base — most reliable delta
              </p>
            </div>
          )}
          {ftScore && gpt4oScore && (
            <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 space-y-1">
              <p className="text-[9px] font-mono uppercase tracking-widest text-white/25">
                vs GPT-4o (synthetic)
              </p>
              <p
                className={cn(
                  "text-[22px] font-semibold leading-none",
                  ftScore.f1 - gpt4oScore.f1 >= 0
                    ? "text-[#22c55e]"
                    : "text-red-400"
                )}
              >
                {ftScore.f1 - gpt4oScore.f1 >= 0 ? "+" : ""}
                {(ftScore.f1 - gpt4oScore.f1).toFixed(1)}
                <span className="text-[13px]"> F1</span>
              </p>
              <p className="text-[10px] text-white/30 leading-snug">
                at {Math.round(gpt4oScore.latency_ms / Math.max(1, ftScore.latency_ms))}
                × lower latency
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ── Entity breakdown tab ──────────────────────────────────────────────────────

function EntitiesTab({
  data,
  f1Mode,
}: {
  data: BenchmarkResults | null;
  f1Mode: F1Mode;
}) {
  if (!data) return null;

  const counts: AnnotationCounts = data.annotationCounts ?? {};
  const liveModelIds = ["pioneer-ft", "gliner-base", "claude35", "gpt4o"].filter(
    (id) => data.models[id]
  );
  const shownMetas = MODEL_META.filter((m) => liveModelIds.includes(m.id));

  const entityRows = ENTITY_TYPES.map((entity) => {
    const scores: Record<string, number> = {};
    for (const id of liveModelIds) {
      const model = data.models[id];
      if (!model) continue;
      const v =
        f1Mode === "partial"
          ? model.perEntityF1Partial?.[entity]
          : model.perEntityF1?.[entity];
      if (v !== undefined) scores[id] = v;
    }
    return { entity, scores, count: counts[entity] ?? 0 };
  }).filter((r) => Object.keys(r.scores).length > 0);

  if (entityRows.length === 0) {
    return (
      <p className="text-[12px] text-white/30 py-8 text-center">
        No per-entity data yet.
      </p>
    );
  }

  function reliabilityBadge(count: number) {
    if (count >= RELIABLE_ANNOTATION_THRESHOLD) return null;
    if (count >= LOW_ANNOTATION_THRESHOLD) {
      return (
        <span className="text-[7px] font-mono text-amber-400/50 border border-amber-400/20 px-1 rounded-full">
          ~{count} ann
        </span>
      );
    }
    return (
      <span className="text-[7px] font-mono text-red-400/50 border border-red-400/20 px-1 rounded-full">
        ~{count} ann · unreliable
      </span>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-start gap-2 rounded-lg border border-white/[0.07] bg-white/[0.02] px-3 py-2.5">
        <Info size={9} className="text-white/25 mt-0.5 shrink-0" />
        <p className="text-[9px] text-white/30 leading-relaxed">
          Per-entity F1 is only meaningful with ≥ 15 annotations. Entity types
          with fewer have 95% CI of ±30–40 points — treat them as directional
          only. Orange = low coverage, Red = insufficient data.
        </p>
      </div>

      <Section
        label={`Per-entity ${f1Mode} F1`}
        hint="Only types with ≥ 15 annotations are statistically reliable"
        Icon={ShieldCheck}
      >
        <div className="overflow-x-auto -mx-1">
          <table className="w-full text-left border-separate border-spacing-y-1">
            <thead>
              <tr>
                <th className="text-[9px] font-mono uppercase tracking-widest text-white/25 pb-2 w-44">
                  Entity type
                </th>
                {shownMetas.map((m) => (
                  <th
                    key={m.id}
                    className="text-[9px] font-mono uppercase tracking-widest pb-2 pr-3 text-right"
                  >
                    <span
                      className={
                        m.isOurs ? "text-[#22c55e]/60" : "text-white/25"
                      }
                    >
                      {m.label.split(" ")[0]}
                    </span>
                  </th>
                ))}
                <th className="text-[9px] font-mono uppercase tracking-widest text-white/25 pb-2 text-right">
                  Δ best
                </th>
              </tr>
            </thead>
            <tbody>
              {entityRows.map((row) => {
                const oursId = shownMetas.find((m) => m.isOurs)?.id;
                const ours = oursId ? (row.scores[oursId] ?? null) : null;
                const allVals = Object.values(row.scores);
                const best = Math.max(...allVals);
                const isUnreliable = row.count < LOW_ANNOTATION_THRESHOLD;
                const delta =
                  ours !== null
                    ? ours -
                      Math.max(
                        0,
                        ...allVals.filter(
                          (_, i) =>
                            Object.keys(row.scores)[i] !== oursId
                        )
                      )
                    : null;

                return (
                  <tr
                    key={row.entity}
                    className={isUnreliable ? "opacity-40" : ""}
                  >
                    <td className="py-2 pr-4">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span
                          className={cn(
                            "w-1.5 h-1.5 rounded-full shrink-0",
                            ENTITY_COLORS[row.entity] ?? "bg-white/20"
                          )}
                        />
                        <span className="text-[11px] text-white/50 font-mono">
                          {row.entity}
                        </span>
                        {reliabilityBadge(row.count)}
                      </div>
                    </td>
                    {shownMetas.map((m) => {
                      const val = row.scores[m.id];
                      const isBest = val === best;
                      return (
                        <td key={m.id} className="py-2 pr-3 text-right">
                          {val !== undefined ? (
                            <span
                              className={cn(
                                "text-[12px] tabular-nums",
                                m.isOurs && isBest
                                  ? "text-[#22c55e] font-semibold"
                                  : m.isOurs
                                  ? "text-[#22c55e]/70"
                                  : isBest
                                  ? "text-white/60 font-medium"
                                  : "text-white/30"
                              )}
                            >
                              {val.toFixed(1)}
                            </span>
                          ) : (
                            <span className="text-[11px] text-white/15">
                              —
                            </span>
                          )}
                        </td>
                      );
                    })}
                    <td className="py-2 text-right">
                      {delta !== null ? (
                        <span
                          className={cn(
                            "text-[11px] font-mono",
                            delta >= 0
                              ? "text-[#22c55e]/60"
                              : "text-red-400/60"
                          )}
                        >
                          {delta >= 0 ? "+" : ""}
                          {delta.toFixed(1)}
                        </span>
                      ) : (
                        <span className="text-[11px] text-white/15">—</span>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        <div className="mt-4 space-y-2 pt-4 border-t border-white/[0.06]">
          <p className="text-[9px] font-mono uppercase tracking-widest text-white/25 mb-3">
            Visual breakdown (reliable types only)
          </p>
          {entityRows
            .filter((r) => r.count >= RELIABLE_ANNOTATION_THRESHOLD)
            .map((row) => {
              const oursId = shownMetas.find((m) => m.isOurs)?.id;
              const ours = oursId ? (row.scores[oursId] ?? null) : null;
              const allVals = Object.values(row.scores);
              const next = Math.max(
                0,
                ...allVals.filter(
                  (_, i) => Object.keys(row.scores)[i] !== oursId
                )
              );
              return (
                <div key={row.entity} className="flex items-center gap-3">
                  <span className="text-[9px] font-mono text-white/30 w-32 shrink-0 truncate">
                    {row.entity}
                  </span>
                  <div className="flex-1 relative h-3 bg-white/[0.04] rounded-full overflow-hidden">
                    <div
                      className="absolute h-full bg-white/10 rounded-full"
                      style={{ width: `${next}%` }}
                    />
                    {ours !== null && (
                      <div
                        className="absolute h-full bg-[#22c55e]/50 rounded-full"
                        style={{ width: `${ours}%` }}
                      />
                    )}
                  </div>
                  <span className="text-[11px] font-semibold text-[#22c55e] w-10 text-right shrink-0">
                    {ours !== null ? ours.toFixed(1) : "—"}
                  </span>
                </div>
              );
            })}
          <p className="text-[9px] text-white/15 mt-1">
            Green = Pioneer fine-tuned · Gray = next-best live model
          </p>
        </div>
      </Section>
    </div>
  );
}

// ── Speed & Cost tab ──────────────────────────────────────────────────────────

function SpeedTab({ data }: { data: BenchmarkResults | null }) {
  const allModels = MODEL_META.map((m) => {
    const score = getScore(m.id, data);
    return score ? { meta: m, latency: score.latency_ms } : null;
  })
    .filter(Boolean)
    .filter((x) => x !== null) as { meta: ModelMeta; latency: number }[];

  const sorted = [...allModels].sort((a, b) => a.latency - b.latency);
  const maxLatency = Math.max(...allModels.map((x) => x.latency), 1);

  const costModels = MODEL_META.map((m) => ({
    meta: m,
    cost: m.costPer1k,
  })).sort((a, b) => a.cost - b.cost);
  const maxCost = Math.max(...costModels.map((x) => x.cost), 1);

  if (!data && sorted.length === 0) return null;

  const ftLatency = data?.models["pioneer-ft"]?.latency_ms;
  const gpt4oLatency = data?.models["gpt4o"]?.latency_ms;
  const claudeLatency = data?.models["claude35"]?.latency_ms;

  return (
    <div className="space-y-6">
      <Section
        label="Inference latency"
        hint="Median per-document latency measured during live evaluation run"
        Icon={Zap}
      >
        <div className="space-y-2">
          {sorted.map(({ meta: m, latency: ms }) => {
            const isPublished = m.source === "published";
            const isLLM = ["gpt4o", "claude35"].includes(m.id);
            return (
              <div
                key={m.id}
                className={cn(
                  "rounded-lg px-3 py-2.5 flex items-center gap-3",
                  m.isOurs
                    ? "bg-[#22c55e]/[0.05] border border-[#22c55e]/20"
                    : "bg-white/[0.02] border border-white/[0.04]"
                )}
              >
                <div className="w-40 shrink-0">
                  <p
                    className={cn(
                      "text-[11px] font-medium",
                      m.isOurs
                        ? "text-white/90"
                        : isPublished
                        ? "text-white/30"
                        : "text-white/50"
                    )}
                  >
                    {m.label}
                  </p>
                  <p
                    className={cn(
                      "text-[9px]",
                      isPublished ? "text-white/18" : "text-white/25"
                    )}
                  >
                    {m.sublabel}
                  </p>
                </div>
                <div className="flex-1 h-1.5 bg-white/[0.06] rounded-full overflow-hidden">
                  <div
                    className={cn(
                      "h-full rounded-full",
                      isLLM
                        ? "bg-white/20"
                        : isPublished
                        ? "bg-white/10"
                        : m.bar
                    )}
                    style={{
                      width: `${Math.max(2, (ms / maxLatency) * 100)}%`,
                    }}
                  />
                </div>
                <span
                  className={cn(
                    "text-[12px] font-semibold tabular-nums w-20 text-right",
                    m.isOurs
                      ? "text-[#22c55e]"
                      : isLLM
                      ? "text-white/30"
                      : isPublished
                      ? "text-white/20"
                      : "text-white/55"
                  )}
                >
                  {ms >= 1000 ? `${(ms / 1000).toFixed(1)}s` : `${ms}ms`}
                  {isPublished && (
                    <span className="text-[8px] ml-0.5 text-white/15">
                      est.
                    </span>
                  )}
                </span>
              </div>
            );
          })}
        </div>
        {ftLatency && gpt4oLatency && (
          <div className="grid grid-cols-2 gap-3 mt-4">
            <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3">
              <p className="text-[9px] font-mono uppercase tracking-widest text-white/25">
                vs GPT-4o
              </p>
              <p className="text-[20px] font-semibold text-[#22c55e]">
                {(gpt4oLatency / Math.max(1, ftLatency)).toFixed(1)}×
              </p>
              <p className="text-[10px] text-white/30">faster per document</p>
            </div>
            {claudeLatency && (
              <div className="rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3">
                <p className="text-[9px] font-mono uppercase tracking-widest text-white/25">
                  vs Claude
                </p>
                <p className="text-[20px] font-semibold text-[#22c55e]">
                  {(claudeLatency / Math.max(1, ftLatency)).toFixed(1)}×
                </p>
                <p className="text-[10px] text-white/30">faster per document</p>
              </div>
            )}
          </div>
        )}
      </Section>

      <Section
        label="Cost per 1,000 documents"
        hint="From published pricing — actual cost varies by document length"
        Icon={DollarSign}
      >
        <div className="space-y-2">
          {costModels.map(({ meta: m, cost }) => {
            const isLLM = ["gpt4o", "claude35"].includes(m.id);
            return (
              <div
                key={m.id}
                className={cn(
                  "rounded-lg px-3 py-2.5 flex items-center gap-3",
                  m.isOurs
                    ? "bg-[#22c55e]/[0.05] border border-[#22c55e]/20"
                    : "bg-white/[0.02] border border-white/[0.04]"
                )}
              >
                <div className="w-40 shrink-0">
                  <p
                    className={cn(
                      "text-[11px] font-medium",
                      m.isOurs ? "text-white/90" : "text-white/50"
                    )}
                  >
                    {m.label}
                  </p>
                </div>
                <div className="flex-1 h-1.5 bg-white/[0.06] rounded-full overflow-hidden">
                  <div
                    className={cn(
                      "h-full rounded-full",
                      isLLM ? "bg-white/20" : m.bar
                    )}
                    style={{
                      width: `${Math.max(0.5, (cost / maxCost) * 100)}%`,
                    }}
                  />
                </div>
                <span
                  className={cn(
                    "text-[12px] font-semibold tabular-nums w-20 text-right",
                    m.isOurs
                      ? "text-[#22c55e]"
                      : isLLM
                      ? "text-white/40"
                      : "text-white/50"
                  )}
                >
                  {cost === 0 ? "free" : `$${cost.toFixed(2)}`}
                </span>
              </div>
            );
          })}
        </div>
        <div className="mt-4 rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 flex items-center justify-between">
          <div>
            <p className="text-[10px] text-white/30">
              Annual savings vs GPT-4o at 50K docs/mo
            </p>
            <p className="text-[11px] text-white/20 mt-0.5">
              ($14.20 − $0.03) × 50,000 × 12
            </p>
          </div>
          <div className="text-right">
            <p className="text-[22px] font-semibold text-[#22c55e]">$8,502</p>
            <p className="text-[9px] text-white/25">saved per year</p>
          </div>
        </div>
      </Section>
    </div>
  );
}

// ── Training Data tab ─────────────────────────────────────────────────────────

function TrainingTab({
  hasFineTunedModel,
}: {
  hasFineTunedModel: boolean;
}) {
  const SYNTH_SOURCES = [
    { agency: "FDA", pct: 27, docs: 94 },
    { agency: "EPA", pct: 18, docs: 61 },
    { agency: "USDA", pct: 14, docs: 48 },
    { agency: "California Prop 65", pct: 12, docs: 42 },
    { agency: "FTC", pct: 11, docs: 38 },
    { agency: "TTB", pct: 10, docs: 34 },
    { agency: "CPSC", pct: 8, docs: 28 },
  ];

  const ENTITY_DIST = [
    { type: "REGULATION", pct: 28, count: 1842, color: "bg-white/40" },
    { type: "CHEMICAL", pct: 22, count: 1446, color: "bg-white/30" },
    { type: "AGENCY", pct: 18, count: 1183, color: "bg-white/22" },
    { type: "PRODUCT", pct: 16, count: 1051, color: "bg-white/16" },
    { type: "DATE", pct: 9, count: 591, color: "bg-[#22c55e]/35" },
    { type: "JURISDICTION", pct: 7, count: 460, color: "bg-white/10" },
  ];

  return (
    <div className="space-y-6">
      <Section
        label="Synthetic data generation pipeline"
        hint="Claude generates regulatory snippets grounded in real source text"
        Icon={FlaskConical}
      >
        <div className="space-y-2">
          {[
            {
              step: "01",
              label: "Seed documents collected",
              desc: "Real FDA/EPA/USDA/FTC regulatory filings as grounding context",
              done: true,
            },
            {
              step: "02",
              label: "Claude generates snippets",
              desc: "300 synthetic regulatory paragraphs with dense entity annotation",
              done: true,
            },
            {
              step: "03",
              label: "Human-in-the-loop review",
              desc: "Annotation QA pass — mislabeled examples removed",
              done: true,
            },
            {
              step: "04",
              label: "Train / validation split",
              desc: "255 train · 45 validation (stratified by agency)",
              done: true,
            },
            {
              step: "05",
              label: "Pioneer fine-tune job",
              desc: "GLiNER2-base fine-tuned on regulatory NER schema via Pioneer Felix API",
              done: hasFineTunedModel,
            },
            {
              step: "06",
              label: "Auto-retrain at 100 corrections",
              desc: "Thumbs on alert cards feed back into training loop",
              done: false,
            },
          ].map((s) => (
            <div key={s.step} className="flex items-start gap-3">
              <div
                className={cn(
                  "w-5 h-5 rounded-full shrink-0 flex items-center justify-center mt-0.5",
                  s.done
                    ? "bg-white/10"
                    : "bg-white/[0.04] border border-white/[0.08]"
                )}
              >
                {s.done ? (
                  <CheckCircle2 size={11} className="text-white/40" />
                ) : (
                  <span className="text-[7px] font-mono text-white/20">
                    {s.step}
                  </span>
                )}
              </div>
              <div>
                <p
                  className={cn(
                    "text-[11px] font-medium leading-none",
                    s.done ? "text-white/70" : "text-white/30"
                  )}
                >
                  {s.label}
                </p>
                <p className="text-[10px] text-white/30 mt-0.5 leading-snug">
                  {s.desc}
                </p>
              </div>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-4 gap-px bg-white/[0.06] rounded-xl overflow-hidden border border-white/[0.07] mt-4">
          <MiniStat label="Total examples" value="300" />
          <MiniStat label="Train split" value="255" />
          <MiniStat label="Val split" value="45" />
          <MiniStat label="Entities labeled" value="6,573" />
        </div>

        {!hasFineTunedModel && (
          <div className="mt-3 rounded-lg border border-white/[0.1] bg-white/[0.03] px-3 py-2">
            <p className="text-[10px] text-white/40">
              Fine-tuned model not configured. Set{" "}
              <code className="text-[9px] bg-white/[0.06] px-1 py-0.5 rounded">
                PIONEER_GLINER_MODEL
              </code>{" "}
              in .env.local to a training job UUID.
            </p>
          </div>
        )}
      </Section>

      <Section
        label="Source agency distribution"
        hint="Training examples by regulatory agency"
        Icon={Database}
      >
        <div className="space-y-2">
          {SYNTH_SOURCES.map((s) => (
            <div key={s.agency} className="flex items-center gap-3">
              <span className="text-[10px] text-white/40 w-36 shrink-0 truncate">
                {s.agency}
              </span>
              <div className="flex-1 h-1.5 bg-white/[0.06] rounded-full overflow-hidden">
                <div
                  className="h-full bg-white/20 rounded-full"
                  style={{ width: `${s.pct}%` }}
                />
              </div>
              <span className="text-[10px] text-white/30 tabular-nums w-8 text-right">
                {s.docs}
              </span>
            </div>
          ))}
        </div>
      </Section>

      <Section
        label="Entity label distribution"
        hint="Across all 6,573 labeled entities in the training set"
        Icon={Activity}
      >
        <div className="space-y-2">
          {ENTITY_DIST.map((e) => (
            <div key={e.type} className="flex items-center gap-3">
              <div className="flex items-center gap-1.5 w-28 shrink-0">
                <span
                  className={cn("w-1.5 h-1.5 rounded-full shrink-0", e.color)}
                />
                <span className="text-[10px] text-white/40 font-mono">
                  {e.type}
                </span>
              </div>
              <div className="flex-1 h-1.5 bg-white/[0.06] rounded-full overflow-hidden">
                <div
                  className={cn("h-full rounded-full", e.color)}
                  style={{ width: `${e.pct * 3}%` }}
                />
              </div>
              <span className="text-[10px] text-white/25 tabular-nums w-14 text-right">
                {e.count.toLocaleString()}
              </span>
              <span className="text-[10px] text-white/20 tabular-nums w-8 text-right">
                {e.pct}%
              </span>
            </div>
          ))}
        </div>
        <div className="mt-4 h-3 rounded-full overflow-hidden flex">
          {ENTITY_DIST.map((e) => (
            <div
              key={e.type}
              className={cn("h-full transition-all", e.color)}
              style={{ width: `${e.pct}%` }}
            />
          ))}
        </div>
      </Section>
    </div>
  );
}

// ── Root export ───────────────────────────────────────────────────────────────

export function BenchmarkPanel() {
  const [activeTab, setActiveTab] = useState<BTab>("overview");
  const [benchData, setBenchData] = useState<BenchmarkResults | null>(null);
  const [cachedAt, setCachedAt] = useState<string | null>(null);
  const [running, setRunning] = useState(false);
  const [runError, setRunError] = useState<string | null>(null);
  const [f1Mode, setF1Mode] = useState<F1Mode>("partial");

  useEffect(() => {
    fetch("/api/benchmark")
      .then((r) => r.json())
      .then(
        (body: {
          data: BenchmarkResults | null;
          cachedAt?: string;
          pioneerJobMetrics?: PioneerJobMetrics | null;
        }) => {
          if (body.data) {
            setBenchData(body.data);
            setCachedAt(body.cachedAt ?? null);
          } else if (body.pioneerJobMetrics) {
            // No comparison run yet, but we have live Pioneer training metrics.
            // Store them in a minimal BenchmarkResults stub so EmptyState can show them.
            setBenchData({
              models: {},
              timestamp: new Date().toISOString(),
              examplesCount: 0,
              hasFineTunedModel: true,
              annotationCounts: {},
              pioneerJobMetrics: body.pioneerJobMetrics,
            });
          }
        }
      )
      .catch(() => {});
  }, []);

  const handleRun = useCallback(async () => {
    setRunning(true);
    setRunError(null);
    try {
      const res = await fetch("/api/benchmark", { method: "POST" });
      const body = (await res.json()) as {
        data?: BenchmarkResults;
        cachedAt?: string;
        error?: string;
      };
      if (!res.ok || body.error) {
        setRunError(body.error ?? `Error ${res.status}`);
      } else if (body.data) {
        setBenchData(body.data);
        setCachedAt(body.cachedAt ?? null);
      }
    } catch (e) {
      setRunError(e instanceof Error ? e.message : "Request failed");
    } finally {
      setRunning(false);
    }
  }, []);

  const hasFineTunedModel = benchData?.hasFineTunedModel ?? false;
  const pioneerJobMetrics = benchData?.pioneerJobMetrics ?? null;
  const hasComparisonData = Object.keys(benchData?.models ?? {}).length > 0;

  return (
    <div className="flex flex-col gap-5">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 mb-1">
          <BarChart3 size={11} className="text-white/30" />
          <h2 className="text-[11px] font-mono uppercase tracking-widest text-white/35">
            Model Benchmarks
          </h2>
        </div>
        <p className="text-[12px] text-white/40 leading-relaxed max-w-xl">
          Two-track evaluation: Pioneer&apos;s held-out validation metrics
          (authoritative, loaded automatically) plus a cross-model comparison on
          25 synthetic examples.
        </p>
      </div>

      {/* F1 mode toggle + eval control */}
      {activeTab !== "training" && (
        <div className="flex items-center justify-between gap-4 flex-wrap">
          <div className="flex items-center gap-2">
            <span className="text-[9px] font-mono uppercase tracking-widest text-white/25">
              F1 mode
            </span>
            <F1Toggle mode={f1Mode} onChange={setF1Mode} />
          </div>
          {hasComparisonData && (
            <EvalHeader
              data={benchData}
              cachedAt={cachedAt}
              running={running}
              error={runError}
              onRun={handleRun}
            />
          )}
        </div>
      )}

      {/* Sub-tabs */}
      <div className="flex gap-1 border-b border-white/[0.06]">
        {BTABS.map((t) => (
          <button
            key={t.id}
            onClick={() => setActiveTab(t.id)}
            className={cn(
              "flex items-center gap-1.5 px-3 py-2 text-[11px] font-medium rounded-t-lg transition-colors",
              activeTab === t.id
                ? "text-white/80 bg-white/[0.05] border border-b-0 border-white/[0.08]"
                : "text-white/30 hover:text-white/55"
            )}
          >
            <t.Icon size={10} />
            {t.label}
          </button>
        ))}
      </div>

      {/* Content */}
      <div>
        {running && activeTab !== "training" && (
          <div className="flex flex-col items-center gap-3 py-12 text-center">
            <RefreshCw size={20} className="text-white/20 animate-spin" />
            <p className="text-[12px] text-white/40">
              Running comparison across all models…
            </p>
            <p className="text-[10px] text-white/20 font-mono animate-pulse">
              GLiNER inference + LLM 5-shot · ~15–60s
            </p>
          </div>
        )}

        {!running && activeTab === "overview" && !hasComparisonData && (
          <EmptyState
            running={running}
            onRun={handleRun}
            pioneerJobMetrics={pioneerJobMetrics}
            baseScore={null}
          />
        )}

        {!running && hasComparisonData && activeTab === "overview" && (
          <OverviewTab
            data={benchData}
            pioneerJobMetrics={pioneerJobMetrics}
            f1Mode={f1Mode}
          />
        )}
        {!running && hasComparisonData && activeTab === "entities" && (
          <EntitiesTab data={benchData} f1Mode={f1Mode} />
        )}
        {!running && activeTab === "entities" && !hasComparisonData && (
          <div className="py-8 text-center">
            <p className="text-[11px] text-white/25">
              Run the comparison to see per-entity breakdown.
            </p>
          </div>
        )}
        {!running && activeTab === "speed" && (
          <SpeedTab data={hasComparisonData ? benchData : null} />
        )}
        {activeTab === "training" && (
          <TrainingTab hasFineTunedModel={hasFineTunedModel} />
        )}
      </div>
    </div>
  );
}
